webtalk_init -webtalk_dir C:/Users/gc998856/SRAM_Controller/Controller_SRAM/SRAM_Controller/SRAM_Controller.sim/sim_1/behav/xsim/xsim.dir/tb_state_machine_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Tue Nov  4 09:52:20 2025" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2019.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2708876" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "174552755_1777500891_210749928_468" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "625f9f18-b8f9-404f-b467-e738cd87ae21" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "253184304f4a4bc180425b1e22bfaae9" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "4" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-2600 CPU @ 3.40GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3392 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "17.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "11 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "2" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.64_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "7076_KB" -context "xsim\\usage"
webtalk_transmit -clientid 1963662140 -regid "174552755_1777500891_210749928_468" -xml C:/Users/gc998856/SRAM_Controller/Controller_SRAM/SRAM_Controller/SRAM_Controller.sim/sim_1/behav/xsim/xsim.dir/tb_state_machine_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/gc998856/SRAM_Controller/Controller_SRAM/SRAM_Controller/SRAM_Controller.sim/sim_1/behav/xsim/xsim.dir/tb_state_machine_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/gc998856/SRAM_Controller/Controller_SRAM/SRAM_Controller/SRAM_Controller.sim/sim_1/behav/xsim/xsim.dir/tb_state_machine_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
