@echo off
REM ****************************************************************************
REM Vivado (TM) v2019.2 (64-bit)
REM
REM Filename    : elaborate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for elaborating the compiled design
REM
REM Generated by Vivado on Tue Nov 04 09:46:29 +0100 2025
REM SW Build 2708876 on Wed Nov  6 21:40:23 MST 2019
REM
REM Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
REM
REM usage: elaborate.bat
REM
REM ****************************************************************************
echo "xelab -wto 253184304f4a4bc180425b1e22bfaae9 --incr --debug typical --relax --mt 2 -L xil_defaultlib -L secureip --snapshot tb_state_machine_behav xil_defaultlib.tb_state_machine -log elaborate.log"
call xelab  -wto 253184304f4a4bc180425b1e22bfaae9 --incr --debug typical --relax --mt 2 -L xil_defaultlib -L secureip --snapshot tb_state_machine_behav xil_defaultlib.tb_state_machine -log elaborate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
